build: pass FFTWF_CFLAGS to arch/common
configure looks up fftw3f with pkg-config for the multi-ARFCN build and
puts FFTWF_LIBS on the link line of the transceiver, but
Transceiver52M/arch/common/Makefile.am, where fft.c lives, never uses
FFTWF_CFLAGS. The compile of fft.c therefore only works where fftw3.h
is in a default include directory.

With fftw from Homebrew on macOS ARM64 the header is in
/opt/homebrew/include, which clang does not search by default:

  arch/common/fft.c:26:10: fatal error: 'fftw3.h' file not found

Add FFTWF_CFLAGS to AM_CFLAGS in that directory. No change where the
header was already found.

Change-Id: I3243ce00bd42a22ff0fbbdd5ff3d00c7441662d0
Signed-off-by: Andrei Gosman <andrei.gosman@gmail.com>